app/routes/main.py
from flask import Flask, Blueprint, render_template, redirect, url_for
from app.models import User, Product

main_bp = Blueprint("main", __name__)

@main_bp.route('/', methods=['GET'])
def index():
    return render_template('/main/index.html')

@main_bp.route('/about', methods=['GET'])
def about():
    return render_template('/main/about.html')

@main_bp.route('/fees', methods=['GET'])
def fees():
    return render_template('/main/fees.html')

@main_bp.route('/@<string:store_url>', methods=['GET'])
def user_store(store_url):
    query = User().custom_query('store_url', store_url).first()
    if not query:
        return redirect(url_for('main.four_o_four'))
    return render_template('/store/store.html', usr=query)

## Error handlers
@main_bp.route('/404', methods=['GET'])
def four_o_four():
    return render_template('/main/404.html')

app/templates/include/footer.html
<footer>
    <p class="footer-text">© uSell 2021</p>
</footer>

app/templates/include/loading.html
<div class="loading-container">
  <svg class="loading" version="1.1"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="25 25 50 50">
    <circle cx="50" cy="50" r="20" fill="none" stroke-width="5" stroke="var(--blue)" stroke-linecap="round" stroke-dashoffset="0" stroke-dasharray="100, 200">
      <animateTransform attributeName="transform" attributeType="XML" type="rotate" from="0 50 50" to="360 50 50" dur="2.5s" repeatCount="indefinite"/>
      <animate attributeName="stroke-dashoffset" values="0;-30;-124" dur="1.25s" repeatCount="indefinite"/>
      <animate attributeName="stroke-dasharray" values="0,200;110,200;110,200" dur="1.25s" repeatCount="indefinite"/>
    </circle>
  </svg>
</div>

app/templates/include/navigation.html
<nav>
    <ul>
        <li>
            <a href="{{url_for('main.index')}}">
                Home
            </a>
        </li>
        <li>
            <a href="{{url_for('main.about')}}">
                About
            </a>
        </li>
        <li>
            <a href="{{url_for('main.fees')}}">
                Fees
            </a>
        </li>
        <li>
            <a href="{{url_for('auth.login')}}">
                Login
            </a>
        </li>
    </ul>
</nav>

app/templates/include/scripts.html
<script src="{{url_for('static', filename='scripts/main.js')}}"></script>

app/templates/include/styles.html
<link href="{{url_for('static', filename='styles/main.css')}}" type="text/css" rel="stylesheet">