app/routes/main.py
from flask import Flask, Blueprint, render_template, redirect, url_for
from app.models import User, Product

main_bp = Blueprint("main", __name__)

@main_bp.route('/', methods=['GET'])
def index():
    return render_template('/main/index.html')

@main_bp.route('/about', methods=['GET'])
def about():
    return render_template('/main/about.html')

@main_bp.route('/fees', methods=['GET'])
def fees():
    return render_template('/main/fees.html')

@main_bp.route('/@<string:store_url>', methods=['GET'])
def user_store(store_url):
    query = User().custom_query('store_url', store_url).first()
    if not query:
        return redirect(url_for('main.four_o_four'))
    return render_template('/store/store.html', usr=query)

## Error handlers
@main_bp.route('/404', methods=['GET'])
def four_o_four():
    return render_template('/main/404.html')

app/routes/seller.py
from flask import Flask, Blueprint, render_template, redirect, url_for, get_flashed_messages, session, jsonify
from flask_login import login_required, current_user
from app.forms import RegisterForm, ProductForm, StoreUrl
from app.models import Product, User, Order
## commit removed simplejson here

seller_bp = Blueprint("seller", __name__)

@seller_bp.route('/dashboard', methods=['GET'])
@login_required
def dashboard():
    usr = User().custom_query('user_id', current_user.get_id()).first()
    
    return render_template('/seller/dashboard.html', form=ProductForm(), store=StoreUrl(), usr=usr, message=get_flashed_messages(), orders=Order().custom_query('user_id' , current_user.get_id()).all())

@seller_bp.route('/url/check/<string:store_url>', methods=['GET'])
@login_required
def check_url(store_url):
    if User().custom_query('store_url', store_url).first():
        return jsonify({'Success': True}), 400
    
    User().update_store_name(current_user.get_id(), store_url)
    return jsonify({'Success': True}), 200

@seller_bp.route('/show/order/<string:orderId>', methods=['GET'])
@login_required
def show_order(orderId):
    result = Order().custom_query('order_id', orderId).first()
    if not result:
        return jsonify({'Success': False}), 400

    
    output = {}
    for item in result.shipping:
        output.update(item.__dict__)

    output['email'] = result.email
    output['status'] = result.status
    output['order_id'] = result.order_id
    output.pop('_sa_instance_state')

    return jsonify(output)

@seller_bp.route('/show/order/<string:order_id>/update/status', methods=['GET'])
@login_required
def mark_order(order_id):
    if not Order().update_status(order_id):
        return jsonify({'Success': False}), 400

    return jsonify({'Success': True}), 200

app/templates/store/order-confirmation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% include 'include/styles.html' %}
    <script src="https://js.stripe.com/v3/"></script>
    <title>uSell - Order #{{order.order_id}}</title>
</head>
<body>
    <section class="shop-content">
        <div class="right">
            <div class="product-heading">
                <h1 id="edit-heading">
                    Order #{{order.order_id}}
                </h1>
            </div>
            <a href="{{url_for('main.user_store', store_url=usr.store_url)}}">
                <h3 class="return-to-seller">Return to sellers page</h3>
            </a>
            {% for item in order.shipping %}
                <div class="view-edit-container order-confirmation">
                    <h1 class="thank-you-header">Thanks for your order, {{item.name}}.</h1>
                    <h3 class="align">Email: {{order.email}}</h3>
                    <h3 class="align">Shipping to:</h3>
                    <p class="shipping-address">
                        {{item.name}}
                        <br>
                        {{item.line_one}}
                        {% if item.line_two is not none %}
                            <br>
                            {{item.line_two}}
                        {% endif %}
                        <br>
                        {{item.city}}
                        <br>
                        {{item.post_code}}
                        <br>
                        {{item.country}}
                    </p>

                    <h5 class="help-with-order">
                        For help with your order, please contact the seller
                    </h5>
                </div>
            {% endfor %}
        </div>
    </section>
</body>
</html>

app/templates/store/store.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="{{url_for('static', filename='img/icons/site-icon.png')}}">
    {% include 'include/styles.html' %}
    <script src="https://js.stripe.com/v3/"></script>
    <title>uSell - @{{usr.store_url}}</title>
</head>
<body>
    {% include 'include/loading.html' %}
    <section class="shop-content">
        <div class="right">
            {% if current_user.is_authenticated %}
                <div class="return-to-dashboard">
                    <a href="{{url_for('seller.dashboard')}}">
                        <h3>Visit Dashboard</h3>
                    </a>
                </div>
            {% endif %}
            <div class="product-heading">
                {% for item in usr.product %}
                    <h1 id="edit-heading">
                        {{item.store_name}}
                    </h1>
                {% endfor %}
            </div>
            
            <div class="view-edit-container">
                {% set desc = namespace(text='') %}
                {% for product in usr.product %}
                    <div class="shop-img">
                        <img src="{{product.image}}" alt="{{usr.store_url}}'s product image">
                    </div>
                
                    <div class="product-title">
                        <h1 id="edit-title">
                            {{product.item_name}}
                        </h1>
                    </div>

                    <div class="product-desc">
                        <h1 id="edit-description">
                            {{item_desc}}
                            {% set desc.text = product.item_desc %}
                        </h1>
                    </div>

                    <div class="product-price">
                        <h1 id="edit-price">
                            {{product.item_currency|replace('gbp', '£')|replace('usd', '$')}}{{product.item_price}}
                        </h1>
                    </div>
                    {% if usr.activated == false %}
                        <div class="payment-not-setup">
                            <h4>{{usr.store_url}} has not setup their account. Once they setup their account, you can purchase.</h4>
                        </div>
                    {% else %}
                        <button onclick="createCheckoutSession('{{usr.store_url}}')" type="button" class="btn-primary btn-checkout">Checkout</button>
                    {% endif %}
                    <div class="product-contact">
                        <h1 id="edit-contact">
                            <a href="mailto:{{product.contact_email}}">
                                {{product.contact_email}}
                            </a>
                        </h1>
                    </div>

                    <div class="product-copyright">
                        <h1 id="edit-copyright">
                            © {{usr.store_url}} 2021
                        </h1>
                    </div>
                {% endfor %}
            
            </div>
        </div>
    </section>
    <script>
        document.querySelector('#edit-description').innerHTML = '{{desc.text}}'
    </script>
    {% include 'include/scripts.html' %}
</body>
</html>