app/routes/payment.py
from flask import Flask, Blueprint, render_template, request, redirect, url_for, flash, get_flashed_messages, session, jsonify
from flask_login import current_user, login_required
from app.models import User, Product
from app.stripe_payments import account_setup, account_query, create_checkout

payment_bp = Blueprint("payment", __name__)

@payment_bp.route('/stripe/link', methods=['GET'])
@login_required
def link_stripe():
    setup = account_setup(User().custom_query('user_id', current_user.get_id()).first().email)
    session['acc_id'] = setup[0]

    return redirect(setup[1])

@payment_bp.route('/stripe/link/validate', methods=['GET'])
@login_required
def stripe_validate():
    if User().custom_query('user_id', current_user.get_id()).first().acc_id:
        return redirect(url_for('seller.dashboard'))
        
    if account_query(session['acc_id'])['charges_enabled']:
        return redirect(url_for('payment.stripe_success'))
    else:
        flash('Semething went wrong. Please try again later')
        return redirect(url_for('seller.dashboard'))

@payment_bp.route('/stripe/link/success', methods=['GET'])
@login_required
def stripe_success():
    User().update_stripe_status(session['acc_id'], current_user.get_id())
    session.pop('acc_id')

    flash('Stripe successfully linked')
    return redirect(url_for('seller.dashboard'))

@payment_bp.route('/checkout/', methods=['GET'])
def checkout():
    usr = User().custom_query('store_url', request.cookies.get('store_url')).first()

    for item in usr.product:
        price = int(item.item_price)*100
        name = item.item_name
        currency = item.item_currency
    
    session['checkoutId'] = create_checkout(usr.acc_id, price, name, currency, usr.user_id)
    
    return jsonify(session['checkoutId'])

app/routes/seller.py
from flask import Flask, Blueprint, render_template, redirect, url_for, get_flashed_messages, session, jsonify
from flask_login import login_required, current_user
from app.forms import RegisterForm, ProductForm, StoreUrl
from app.models import Product, User, Order
## commit removed simplejson here

seller_bp = Blueprint("seller", __name__)

@seller_bp.route('/dashboard', methods=['GET'])
@login_required
def dashboard():
    usr = User().custom_query('user_id', current_user.get_id()).first()
    
    return render_template('/seller/dashboard.html', form=ProductForm(), store=StoreUrl(), usr=usr, message=get_flashed_messages(), orders=Order().custom_query('user_id' , current_user.get_id()).all())

@seller_bp.route('/url/check/<string:store_url>', methods=['GET'])
@login_required
def check_url(store_url):
    if User().custom_query('store_url', store_url).first():
        return jsonify({'Success': True}), 400
    
    User().update_store_name(current_user.get_id(), store_url)
    return jsonify({'Success': True}), 200

@seller_bp.route('/show/order/<string:orderId>', methods=['GET'])
@login_required
def show_order(orderId):
    result = Order().custom_query('order_id', orderId).first()
    if not result:
        return jsonify({'Success': False}), 400

    
    output = {}
    for item in result.shipping:
        output.update(item.__dict__)

    output['email'] = result.email
    output['status'] = result.status
    output['order_id'] = result.order_id
    output.pop('_sa_instance_state')

    return jsonify(output)

@seller_bp.route('/show/order/<string:order_id>/update/status', methods=['GET'])
@login_required
def mark_order(order_id):
    if not Order().update_status(order_id):
        return jsonify({'Success': False}), 400

    return jsonify({'Success': True}), 200

app/templates/seller/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="{{url_for('static', filename='img/icons/site-icon.png')}}">
    {% include 'include/styles.html' %}
    <title>uSell</title>
</head>
<body>
    <main>
        <section class="container">
            <div class="mobile-menu">
                <i onclick="openNav()" class="fas fa-bars"></i>
            </div>
            <div class="left">
                <i onclick="closeNav()" class="far fa-times-circle close-menu"></i>
                <div class="dashboard-links">
                    <ul>
                        <li onclick="showStore()">
                            Store
                        </li>
                        <li onclick="showOrders()">
                            Orders
                        </li>
                        <li onclick="showSettings()">
                            Settings
                        </li>
                        
                        {% if usr.activated == false %}
                            <li class="stripe-li">
                                <a href="{{url_for('payment.link_stripe')}}">
                                    <button type="button" class="btn-primary btn-stripe">Connect Stripe</button>
                                </a>

                                
                            </li>
                        {% endif %}

                        {% if message !=[] %}
                                <li>
                                    <div class="flashed-message-success">
                                        {{message[0]}}
                                    </div>
                                </li>
                        {% endif %}
                    </ul>
                </div>
                <div class="edit-product-wrapper dashboard">
                    <div class="return-home">
                        <h5 onclick="goHome()"><i class="fas fa-arrow-circle-left"></i> Back</h5>
                    </div>
                    {% set product_id = namespace('') %}
                    {% for item in usr.product %}
                        {% set product_id.value = item.product_id %}
                    {% endfor %}
                    <form method="POST" class="edit-form" autocomplete="off" action="/editor/update/{{product_id.value}}" enctype="multipart/form-data">
                        <div class="add-product-details">
                            {% for product in usr.product %}
                                <div class="form-input-wrapper">
                                    <label for="store-name">Store Name</label>
                                    {{form.store_name(id="store-heading", value=product.store_name)}}
                                </div>

                                <div class="form-input-wrapper">
                                    <label for="item-name">Item Name</label>
                                    {{form.item_name(id="item-name", value=product.item_name)}}
                                </div>

                                <div class="form-input-wrapper">
                                    <label for="item-description">Item Description</label>
                                    {{form.item_desc(id="edit-textarea", required="True")}}
                                    {% set textarea = product.item_description %}
                                </div>

                                <div class="form-input-wrapper">
                                    <label for="item-price">Price</label>
                                    <div class="form-price-wrapper">
                                        {{form.item_currency(id="currency", value=product.item_currency)}}
                                        {{form.item_price(id="store-price", value=product.item_price)}}
                                    </div>
                                </div>

                                <div class="form-input-wrapper">
                                    <label for="item-image">Image</label>
                                    <div class="edit-form-img-upload">
                                        <div class="preview-img">
                                            <img src="{{product.image}}" id="preview-uploaded-img" alt="{{usr.store_url}}'s product image">
                                        </div>
                                        <h6 id="file-plus">+</h6>
                                        {{form.item_img(class="upload-img-input", onchange="loadFile(event), changeInput(event)", required="false", accept="image/*")}}
                                    </div>
                                </div>

                                <div class="form-input-wrapper">
                                    <label for="user-email">Contact Email</label>
                                    {{form.contact_email(id="store-contact", value=product.contact_email)}}
                                    <div class="contact-email-error">
                                        Please enter a valid email
                                    </div>
                                </div>
                            {% endfor %}
                            
                            <button onclick="validateEditForm()" type="button" class="btn-primary create-product-next">Update Product</button>
                        </div>
                    </form>
                </div>
                <div class="order-tab">
                    <div class="return-home">
                        <h5 onclick="goHome()"><i class="fas fa-arrow-circle-left"></i> Back</h5>
                    </div>
                    {% if orders == [] %}
                        <div class="no-orders">
                            <h1>You have no orders</h1>
                        </div>
                    {% endif %}
                    <div class="all-orders">
                        {% for i in orders %}
                            <a onclick="fetchOrder('{{i.order_id}}')">
                                <div class="order-block">
                                    <div class="order-block-top">
                                        <h4>Order <span class="color-grey">#{{i.order_id}}</span></h4>
                                    </div>
                                    <div class="order-block-middle">
                                        <h4>Email: <span class="color-grey">{{i.email}}</span></h4>
                                        <h4>Total: <span class="color-grey">{{i.currency|replace('gbp', '£') | replace('usd', '$')}}{{i.price_paid}}</span></h4>
                                    </div>
                                    <div class="order-block-bottom">
                                        <h4 class="order-status-{{i.order_id}}">Status: <span class="color-green">{{i.status}}</span></h4>
                                    </div>
                                </div>
                            </a>
                        {% endfor %}
                    </div>
                </div>
                <div class="settings">
                    <div class="return-home">
                        <h5 onclick="goHome()"><i class="fas fa-arrow-circle-left"></i> Back</h5>
                    </div>
                    <form class="url-form">
                        <div class="form-input-wrapper">
                            <label for="url">Custom Url</label>
                            <p class="custom-url">
                                {% if usr.store_url != None %}
                                    <a id="url-anchor" target="_blank" href="/@{{usr.store_url}}">https://usell.com/@{{usr.store_url}}</a>
                                {% else %}
                                    <a id="url-anchor" target="_blank" href="/@{{usr.store_name}}">https://usell.com/</a>
                                {% endif %}
                            </p>
                            {{store.store_url}}
                            <div class="store-url-error">
                                Minimum 3 characters 
                            </div>
                        </div>
                        <div class="url-error">
                            <p>Store Name is not available.</p>
                        </div>
                        <button onclick="checkStoreAvailability()" type="button" class="btn-primary">Check Availability</button>
                    </form>

                    {% if message != []%}
                        <div class="flashed-message">
                            {% if message[0] != 'Stripe successfully linked' %}
                                {{message[0] }}
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="right">
                <div class="product-heading">
                    {% for item in usr.product %}
                        <h1 id="edit-heading">
                            {{item.store_name}}
                        </h1>
                    {% endfor %}
                </div>
                    
                <div class="view-edit-container">
                    {% set textarea = namespace(textarea = '') %}
                    {% for i in usr.product %}
                        <div class="view-edit-img">
                            <img src="{{i.image}}" id="view-img" alt="{{usr.store_url}}'s product image">
                        </div>
                    
                        <div class="product-title">
                            <h1 id="edit-title">
                                {{i.item_name}}
                            </h1>
                        </div>

                        <div class="product-desc">
                            <h1 id="edit-description">
                                {{i.item_desc}}
                                {% set textarea.text = i.item_desc %}
                            </h1>
                        </div>

                        <div class="product-price">
                            <h1 id="edit-price">
                                {{i.item_currency|replace('gbp', '£')|replace('usd', '$')}}{{i.item_price}}
                            </h1>
                        </div>

                        <div class="product-contact">
                            <h1 id="edit-contact">
                                {{i.contact_email}}
                            </h1>
                        </div>

                        <div class="product-copyright">
                            <h1 id="edit-copyright">
                                © {{usr.store_name}} 2021
                            </h1>
                        </div>
                    {% endfor %}

                </div>

                <div class="show-order-information">
                    <h2 id="view-order-number"></h2>
                    <h4 id="view-order-email"></h4>
                    <h4>SHIPPING TO:</h4>
                    <p id="view-order-shipping">
                    </p>
                    <button type="button" class="btn-primary order-complete">
                        MARK AS COMPLETE
                    </button>

                
                    <div class="order-update-fail">
                        <h3>Something went wrong. Please try again later</h3>
                    </div>
                    <div class="order-update-success">
                        <h3>Order has been marked as fulfilled.</h3>
                    </div>
                </div>
            </div>
        </section>
    </main>
    {% include 'include/scripts.html' %}
    <script>
        document.querySelector('#edit-textarea').value = "{{textarea.text}}";
    </script>
</body>
</html>